config/routes.rb
Rails.application.routes.draw do
  get 'scholars/index'
  get 'scholars/new'
  get 'scholars/edit'
  delete 'scholars/:id', to: 'scholars#destroy', as: 'scholar'
  # get 'scholars/destroy'

  get 'faculties/index'
  get 'faculties/new'
  get 'faculties/show'
  get 'principals/index'
  get 'principals/new'
  get 'principals/show'

  resources :books
    # get 'books/index'
    # get 'books/show'
    # get 'books/new'
    # get 'books/create'
    # get 'books/edit'
    # get 'books/update'
    # get 'books/destroy'
  namespace :management do
    resources :students
    resources :teachers
    resources :admins
    resources :books
    
    root to: "admins#index"
  end
  # get 'user/index
  # devise_for :teachers
  # devise_for :students
  # resources :admins
  # devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "user#index"
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }

  # Defines the root path route ("/")
 
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def new
  end

  def show
  end

  def destroy
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/index.html.erb
<h1>Teachers List</h1>

    <table>
        <tr>
            <th>Name</th>
            <th>E-Mail</th>
            <th>Contact Number</th>
            <th>Subject</th>
            <% if admin_signed_in? %>
                <th>Edit</th>
            <% end %>
        </tr>
            <tr>
            <td><%= current_teacher.full_name %></td>
            <td><%= current_teacher.email %></td>
            <td><%= current_teacher.contact_number %></td>
            <td><%= current_teacher.subject %></td>
            <% if admin_signed_in? %>
            <td><%= link_to "Edit", edit_teacher_registration_path %></td>

            </tr>
        <% end %>
    </table>

    

app/views/faculties/new.html.erb
<h1>Faculties#new</h1>
<p>Find me in app/views/faculties/new.html.erb</p>

app/views/faculties/show.html.erb
<h1><%= current_teacher.full_name %></h1>
<p><%= @teacher.email %></p>
<p><%= @teacher.contact_number %></p>
<p><%= @teacher.full_name%></p>
<p><%= @teacher.subject %></p>
<%= button_to "Delete", faculty_path(@teacher), method: :delete, data: { confirm: "Are you sure?" } %>