config/routes.rb
Rails.application.routes.draw do
  get 'scholars/index'
  get 'scholars/new'
  get 'scholars/edit'
  delete 'scholars/:id', to: 'scholars#destroy', as: 'scholar'
  # get 'scholars/destroy'

  get 'faculties/index'
  get 'faculties/new'
  get 'faculties/show'
  get 'principals/index'
  get 'principals/new'
  get 'principals/show'

  resources :books
    # get 'books/index'
    # get 'books/show'
    # get 'books/new'
    # get 'books/create'
    # get 'books/edit'
    # get 'books/update'
    # get 'books/destroy'
  namespace :management do
    resources :students
    resources :teachers
    resources :admins
    resources :books
    
    root to: "admins#index"
  end
  # get 'user/index
  # devise_for :teachers
  # devise_for :students
  # resources :admins
  # devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "user#index"
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }

  # Defines the root path route ("/")
 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.erb
<% if admin_signed_in? %>
    <div>Welcome <%= current_admin.email %></div>
    <div class="log_in">
      <%= button_to "Admin Dashboard",  management_root_path, method: :get, class: "btn-custom" %> <br>
      <%= button_to "Sign out", destroy_admin_session_path, method: :delete, class: "btn-custom" %>
      <%= link_to "edit", edit_admin_registration_path %>
    </div>
<% elsif teacher_signed_in? %>
<div class="log_in">
    <%= link_to "Teacher Details",  faculties_index_path %> <br>
    <%= link_to "Student Details",  scholars_index_path %>
    <%= button_to "Sign out", destroy_teacher_session_path, method: :delete, class: "btn-custom" %>
    <%= link_to "edit", edit_teacher_registration_path %>
</div>
<% elsif student_signed_in? %>
<div class="log_in">
    <%= link_to "Student Details",  scholars_index_path %> <br>
    <%= link_to "Books Details",  books_path %> <br>
    <%= button_to "Sign out", destroy_student_session_path, method: :delete, class: "btn-custom" %>
    <%= link_to "edit", edit_student_registration_path %>
</div>
<% else %>
  <div class="heading">
  <h1>School Management System</h1> <br/>
  <h2>Select your role:</h2>
  </div>
  <div class="button-container">
  <%= button_to "Admin",   new_admin_session_path , class: "btn-custom" %>
  <%= button_to "Teacher", new_teacher_session_path, class: "btn-custom" %>
  <%= button_to "Student",  new_student_session_path, class: "btn-custom" %>
</div>
<% end %>