config/routes.rb
Rails.application.routes.draw do
  get 'scholars/index'
  get 'scholars/new'
  get 'scholars/edit'
  delete 'scholars/:id', to: 'scholars#destroy', as: 'scholar'
  # get 'scholars/destroy'

  get 'faculties/index'
  get 'faculties/new'
  get 'faculties/show'
  get 'principals/index'
  get 'principals/new'
  get 'principals/show'

  resources :books
    # get 'books/index'
    # get 'books/show'
    # get 'books/new'
    # get 'books/create'
    # get 'books/edit'
    # get 'books/update'
    # get 'books/destroy'
  namespace :management do
    resources :students
    resources :teachers
    resources :admins
    resources :books
    
    root to: "admins#index"
  end
  # get 'user/index
  # devise_for :teachers
  # devise_for :students
  # resources :admins
  # devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "user#index"
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    registrations: 'teachers/registrations'
  }
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'students/registrations'
  }

  # Defines the root path route ("/")
 
end

app/controllers/scholars_controller.rb
class ScholarsController < ApplicationController
  def index
    @student = Student.all
  end

  def new
  end

  def edit
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to root_path
  end
  private
    def student_params
      params.require(:student).permit(:email, :full_name, :parent_name, :contact_number)
    end
end

app/helpers/scholars_helper.rb
module ScholarsHelper
end

app/views/scholars/edit.html.erb
<h1>Scholars#edit</h1>
<p>Find me in app/views/scholars/edit.html.erb</p>

app/views/scholars/index.html.erb
<h1>Student List</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>E-Mail</th>
            <th>Contact Number</th>
            <th>Parent Name</th>
            <% if teacher_signed_in? or admin_signed_in?%>
                <th>Edit</th>
            <% end %>
            <% if teacher_signed_in? or admin_signed_in?%>
            <th>Destroy</th>
            <% end %>
        </tr>
        <% @student.each do |students| %>
            <tr>
            <td><%= students.full_name %></td> 
           <td><%= students.email %></td>
            <td><%= students.contact_number %></td>
            <td><%= students.parent_name %></td>
            <% if teacher_signed_in? or admin_signed_in? %>
            <td><%= link_to "Edit", edit_student_registration_path %></td>
            <% end %>
            <% if teacher_signed_in? or admin_signed_in?%>
            <td><%= link_to "Destroy", scholar_path(students), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to destroy student ?"
              } %></td>
              <% end %>
            </tr>
        <% end %>
    </table>

app/views/scholars/new.html.erb
<h1>Scholars#new</h1>
<p>Find me in app/views/scholars/new.html.erb</p>